
sudo: false

addons:
  apt:
    packages:
      - libgmp-dev

cache:
  directories:
  - $HOME/.stack/

before_install:
  # stack
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - ./travis/long stack --no-terminal --skip-ghc-check setup
  - ./travis/long stack --no-terminal --skip-ghc-check test --only-snapshot --fast --pedantic

script:
  - stack --no-terminal --skip-ghc-check test
